const CALENDAR_PREV_MONTH='CALENDAR_PREV_MONTH';
const CALENDAR_NEXT_MONTH='CALENDAR_NEXT_MONTH';
const CALENDAR_PREV_YEAR='CALENDAR_PREV_YEAR';
const CALENDAR_NEXT_YEAR='CALENDAR_NEXT_YEAR';
const CALENDAR_EDIT_YEAR='CALENDAR_EDIT_YEAR';
const CALENDAR_SHOW_DETAIL='CALENDAR_SHOW_DETAIL';