export const DISPLAY_DETAILS_DAY = 'DISPLAY_DETAILS_DAY';
export const SHOW_MOBILE_NAV_MENU = 'SHOW_MOBILE_NAV_MENU';
export const HIDE_MOBILE_NAV_MENU = 'HIDE_MOBILE_NAV_MENU';

export const FETCH_POSTS ='FETCH_POSTS';
export const FETCH_POSTS_SUCCESS= 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL= 'FETCH_POSTS_FAIL';
